Add new ShopEntryColors and ShopEntryRenderImage
Fortnite-API/py-wrapper pull request #23
Opened 2024-09-03 09:46 UTC by Luc1412

This pull requests adds support for the new `ShopEntryColors` and `ShopEntryRenderImage`. Additionally `MaterialInstance` also got a new `product_tag` attribute.

2024-09-03 12:32 UTC, Luc1412 commented on fortnite_api/enums.py
> +    ROCKET_RACING = 'Product.DelMar'
We got an issue here. Mainly `DelMar` is used. But in rare cases it's `Delmar`. How do we wanna handle this?

2024-09-04 02:01 UTC, trevorflahardy requested changes
Overall looks good, just a few small things

2024-09-04 02:01 UTC, trevorflahardy commented on fortnite_api/shop.py
> +        self.text_background_color: str = data['textBackgroundColor']
More fitting names here may be `color_first`, `color_second`, `color_third`, or a different convention relating to their location in the gradient.

I feel that the numbers in the variable names are cumbersome, what do you think?

2024-09-04 02:01 UTC, trevorflahardy commented on fortnite_api/shop.py
> +    image: :class:`fortnite_api.Asset`
Provide an example here if you could. I know what this is a file name but personally have no idea what that could be - may be helpful to users like myself.

2024-09-04 02:01 UTC, trevorflahardy commented on fortnite_api/shop.py
>      br: List[:class:`fortnite_api.CosmeticBr`]
Previous implementations of anything color related provide both spellings as attributes: "color"/"colors" and "colour"/"colours"

To keep with consistent conventions this should be updated to have both attributes.

2024-09-04 02:01 UTC, trevorflahardy commented on fortnite_api/enums.py
> +    ROCKET_RACING = 'Product.DelMar'
I see 6d83a1e and I think it's the best solution that aligns well with what is already in place in other areas of the library. Resolving as it is now outdated and handled well.

2024-09-05 07:35 UTC, Luc1412 commented on fortnite_api/shop.py
> +        self.text_background_color: str = data['textBackgroundColor']
The gradient usually works like this: color1 is the top color of the gradient, color2 is the middle color of the gradient (optional) and color 3 is the bottom color of the gradient. In this case I just took the original names. What do you think?

2024-09-05 07:40 UTC, Luc1412 commented on fortnite_api/shop.py
>      br: List[:class:`fortnite_api.CosmeticBr`]
There are multiple occasions of color, but only BannerColor.color got an alias. All other occasions of color got no alias.

2024-09-09 08:29 UTC, Luc1412 commented on fortnite_api/shop.py
> +        self.text_background_color: str = data['textBackgroundColor']
Update:
If only color1 and color3 are available,  color1 is the top color and color 3 the bottom one.
If all 3 colors are available, color1 is the top color, color3 becomes the middle color and color2 the bottom color.

So what do you think?

2024-09-09 08:32 UTC, Luc1412 commented on fortnite_api/shop.py
> +    image: :class:`fortnite_api.Asset`
You refer to the `file_name`? 'm not 100% sure, but it seems fileName refers to the name of the file within the game files of the render image.

So what example you thought about?

2024-09-23 15:30 UTC, trevorflahardy requested changes
Overall looks good, just some small things I see - solid work.

2024-09-23 15:30 UTC, trevorflahardy commented on fortnite_api/shop.py
> +class ShopEntryOfferTag(ReconstructAble[Dict[str, Any], HTTPClientT]):
This class should also inherit `abc.Hashable` for `hash(x)` and comparison operations. Documentation should be updated accordingly too.

2024-09-23 15:30 UTC, trevorflahardy commented on fortnite_api/shop.py
> +    image: :class:`fortnite_api.Asset`
Apologies, I wasn't clear enough - Yes I'm referring to the `file_name` attribute. An example filename from the API so the user is aware of what the string looks like may be helpful. For example, `file.png` could be an example of a filename

2024-09-23 15:30 UTC, trevorflahardy commented on fortnite_api/shop.py
>      br: List[:class:`fortnite_api.CosmeticBr`]
I see, I remember it being different. Either all occurrences of the alias `colour` should be removed (in a new PR) or all existing `color`s should be updated with aliases (also in a new PR) - all or nothing.

Which do you think is the best course of action?

2024-09-23 15:33 UTC, trevorflahardy commented on fortnite_api/shop.py
> +        self.text_background_color: str = data['textBackgroundColor']
I see, because of the variability of `color2` I think that the current naming convention is the best. It would be cumbersome otherwise 👍

2024-09-23 21:02 UTC, Luc1412 commented on fortnite_api/shop.py
> +    image: :class:`fortnite_api.Asset`
`file_name` refers to the name within the game files, but not the `image`. E.g. `T-Featured-Pickaxes-SleepyTimePickaxe`. This info isn't useful for 99% of the users and might be only relevant for datamining related tasks.

Not sure if we require more docs on this one. If you got something specific in mind, fell free to suggest a change.

2024-09-23 21:04 UTC, Luc1412 commented on fortnite_api/shop.py
>      br: List[:class:`fortnite_api.CosmeticBr`]
I feel like it's pretty unnecessary. Intellisense should provide enough help. I'd say we can remove all `colour` appearences in 3.1.0

2024-09-24 23:11 UTC, trevorflahardy commented on fortnite_api/shop.py
>      br: List[:class:`fortnite_api.CosmeticBr`]
Sounds good, agreed.

2024-09-24 23:17 UTC, trevorflahardy commented on fortnite_api/shop.py
> +    image: :class:`fortnite_api.Asset`
Ah, I see - I think that should be clarified in the docs for sure. Maybe something like:
```suggestion
    file_name: :class:`str`
        The internal file name of the rendered image. Refers to the name within the game files and **not** the :attr`image`. An example of this is ``T-Featured-Pickaxes-SleepyTimePickaxe``.
    image: :class:`fortnite_api.Asset`
```

2024-09-25 21:32 UTC, trevorflahardy requested changes
Good to go after this 👍

2024-09-25 21:32 UTC, trevorflahardy commented on fortnite_api/shop.py
> +    text_background_color: Optional[:class:`str`]Optional[:class:`str`]
```suggestion
    text_background_color: Optional[:class:`str`]
```

2024-09-25 21:32 UTC, trevorflahardy commented on fortnite_api/shop.py
> +        )
This attribute was never documented.

2024-09-25 21:32 UTC, trevorflahardy commented on tests/test_async_methods.py
> +            assert offer_tag.text
Duplicated code,
```suggestion
```

2024-09-25 22:13 UTC, trevorflahardy approved these changes

2024-09-25 22:40 UTC, merged