Opt in documentation
Fortnite-API/py-wrapper pull request #28
Opened 2024-10-12 17:42 UTC by trevorflahardy

## Summary

This PR updates documentation to include information regarding the newly added `ResponseFlags` class in the library.

- Updates the migration guide to include the `response_flags` parameter in the client.
- Creates a `Response Flags` section in the documentation describing what response flags are and how to use them.
- Creates a `.. opt-in` sphinx directive that marks an attribute as needing to be marked-in.
- Updates all relevant attributes with said sphinx directive. 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2024-10-13 14:30 UTC, Luc1412 requested changes
Looks good, but directive is applied to attributes that are not part of the opt-in.

2024-10-13 14:30 UTC, Luc1412 commented on fortnite_api/shop.py
> +        .. opt-in:: INCLUDE_PATHS
This field isn't affected by opt-in params.

2024-10-13 14:30 UTC, Luc1412 commented on fortnite_api/playlist.py
> +        .. opt-in:: INCLUDE_PATHS
Both fields are not affected by opt-in params.

2024-10-13 14:30 UTC, Luc1412 commented on docs/response_flags.rst
I think we should emphasize the user to only use the required opt-in parameters they actually need. And how the user benefits from it. (e.g. perfomance, bandwith)

2024-10-13 14:30 UTC, Luc1412 commented on fortnite_api/cosmetics/br.py
> +        .. opt-in:: INCLUDE_PATHS
This attribute seems to not present anymore. I need to check back with Officer about it's status.

2024-10-19 10:12 UTC, Luc1412 commented on fortnite_api/cosmetics/br.py
> +        .. opt-in:: INCLUDE_PATHS
Officer recommends to keep this for now

2024-10-19 16:00 UTC, trevorflahardy commented on docs/response_flags.rst
Added in 5270136 in an `important` directive that explains why you should not enable all flags by default, an example of it in action, and how you should develop with response flags in mind.

2024-10-19 20:43 UTC, Luc1412 approved these changes
lgtm

2024-10-19 20:43 UTC, merged